spring:
  application:
    name: testCamelCamundaBoundary

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
    driverClassName: org.postgresql.Driver

camunda.bpm:
  database:
    schema-update: true
    type: postgres
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  webapp:
    index-redirect-enabled: false
  job-execution:
    deployment-aware: true
  history-level: auto

server:
  port: ${TOMCAT_PORT:8080}

logging:
  file: application.log
  level:
    org:
      apache:
        http: debug


